Prototipo/Prototipo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("Repositorio.urls"))
] 
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Prototipo/Repositorio/urls.py
from django.urls import path
from .views import *

app_name = "Repositorio"
urlpatterns = [
    path('', Login, name='Login'),
    path('home/<int:username_id>/<str:code>/', Home, name='home'),
    path('register/', Registrarse, name="Registrarse"),
    path('sala1/<str:id_user>', sala1, name="sala1"),
    path('checkview1', Chekview1, name="checkview1"),
    path('checkview2', Chekview2, name="checkview2"),
    path('sala2/', sala2, name='sala2'),
    path('checkview3', Checkview3, name='checkview3'),
    path('checkview4', Checkview4, name='checkview4'),
    path('send', send, name='send'),
    path('send2', send2, name='send2'),
    path('getMessages/<str:room>/', getMessages, name='getMessages'),
    path('home/<int:username_id>/<str:code>/subir/', subir, name='subir'),
    path('home/<int:username_id>/<str:code>/archivos/', Mostrar_Archivos, name='archivos'),
    path('home/<int:username_id>/<str:code>/mis_archivos/', Mis_Archivos, name='mis_archivos'),
    path('home/resultados/', Resultado_Busquedas, name='resultados'),
    path('home/archivos/<int:id_post>/<int:username_id>/', Archivo_personal, name='archivo_personal'),
    path('archivo', DescargarArchivoView.as_view(), name='archivo_post'),
]

Prototipo/Repositorio/models.py
from django.db import models

# Create your models here.

class ModelBase(models.Model):
    id = models.AutoField(primary_key=True, editable=False)
    tiempo = models.DateTimeField(auto_now_add=True)
    actualizar = models.DateTimeField(auto_now=True)

    class Meta:
	    abstract = True

class Usuario(ModelBase):
    user_name = models.CharField(max_length=30)
    user_password = models.CharField(max_length=100)
    user_image = models.ImageField(upload_to="images/", null=True)

    def __str__(self):
        return self.user_name

    class Meta:
        verbose_name = "Usuario"
        verbose_name_plural = "Usuarios"

class Canal(ModelBase):
    canal_users = models.ManyToManyField(Usuario, blank=True, through="Membership")
    canal_code = models.CharField(max_length=6, editable=False, default="000aaa")
    canal_name = models.CharField(max_length=100, default="Grupo de Amigos", editable=True)

    def __str__(self):
        return self.canal_code
    
    class Meta:
        verbose_name = "Canales"
        verbose_name_plural = "Canales"

class Archivo(ModelBase):
    archivo = models.FileField(upload_to="pdfs/" ,null=False, blank=True )
    titulo = models.CharField(max_length=150, editable=True)
    descripcion = models.CharField(max_length=1000000, editable=True)
    categoria = models.CharField(max_length=200)
    tipo = models.CharField(max_length=20)
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    canal = models.ForeignKey(Canal, on_delete=models.CASCADE)
    likes = models.IntegerField(default=0)
    vistas = models.IntegerField(default=0)
    comments = models.IntegerField(default=0)
    lista = list()

    def __str__(self):
        return self.titulo
    
    class Meta:
        verbose_name = "Archivo"
        verbose_name_plural = "Archivos"

class Comentarios(ModelBase):
    cm_texto = models.CharField(max_length=1000000)
    cm_archivo = models.ForeignKey(Archivo, on_delete=models.CASCADE)
    cm_user = models.CharField(max_length=1000000, default='desconocido')

    def __str__(self):
        return self.cm_texto

    class Meta:
        verbose_name = "Comentario"
        verbose_name_plural = "Comentarios"

class Mensaje(ModelBase):
    ms_text = models.CharField(max_length=1000000)
    ms_user = models.CharField(max_length=1000000)
    ms_canal = models.ForeignKey(Canal, on_delete=models.CASCADE)

    def __str__(self):
        return self.ms_text

    class Meta:
        verbose_name = "Mensajes"
        verbose_name_plural = "Mensajes"


class Membership(ModelBase):
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    canal = models.ForeignKey(Canal, on_delete=models.CASCADE)

Prototipo/Repositorio/views.py
from distutils import archive_util
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from .models import *
import random
from datetime import datetime
from django.core.exceptions import ObjectDoesNotExist
from django.views.generic.base import View
# Create your views here.
#no olvides hacer codigo para el login y eliminar salas inecesarias

def Home(request, username_id, code):
    usuario = Usuario.objects.get(id=username_id)
    sala = Canal.objects.get(canal_code=code)
    messages = Mensaje.objects.filter(ms_canal=sala)

    integrantes = []

    for i in Membership.objects.all():
        if (i.canal == sala) and (i.usuario!=usuario):
            integrantes.append(i.usuario)

    data = {
        'usuario': usuario,
        'sala': sala,
        'messages': messages,
        'miembros': integrantes
    }
    return render(request, "Home.html", data)

def Login(request):
    return render(request, "form_login.html")

def Registrarse(request):
    return render(request, "form_register.html")

def sala1(request, id_user):
    data = {
        "id_user" : id_user,
    }
    return render(request, "canal_main.html", data)

def sala2(request):
    identificador = request.POST["id_user"]
    identificador = int(identificador)
    code= ""
    code_value = []
    valores = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9"]
    
    for i in range(6):
        num = random.randint(0, 34) 
        code_value.append(num)

    for i in code_value:
        for j in range(34):
            if i == j:
                code = code + valores[j]
                break

    code = code.upper()

    sala = Canal.objects.create(canal_code=code)
    sala.save()

    data = {
        'identificador': identificador,
        'codigo': code
    }

    return render(request, "canal_create.html", data)

def subir(request, username_id, code):
    data = {
        'username_id': username_id,
        'code': code
    }
    return render(request, "subir_archivo.html", data)

def Mis_Archivos(request, username_id, code):
    user = Usuario.objects.get(id=username_id)
    archivos = Archivo.objects.filter(usuario=user)
    data = {
        'username_id': username_id,
        'code': code,
        'archivos':archivos,
        'content_type':'text/plain'
    }
    return render(request, "mostrar_archivos.html", data)

def Mostrar_Archivos(request, username_id, code):
    sala = Canal.objects.get(canal_code=code)
    archivos = Archivo.objects.filter(canal=sala)
    data = {
        'username_id': username_id,
        'code': code,
        'archivos':archivos,
        'content_type':'text/plain'
    }
    return render(request, "mostrar_archivos.html", data)

def Resultado_Busquedas(request):
    if request.POST["palabra"]:
        palabra = request.POST["palabra"]
        username_id = request.POST["username_id"]
        code = request.POST["code"]
        sala = Canal.objects.get(canal_code=code)
        arc = Archivo.objects.filter(canal=sala)

        archivos = []
        palabra = palabra.lower()
        for i in arc:
            if palabra in i.titulo.lower():
                archivos.append(i)

        data = {
            'username_id': username_id,
            'code': code,
            'archivos':archivos,
            'content_type':'text/plain'
        }
        return render(request, "mostrar_archivos.html", data)

    else:
        return HttpResponse("No introdujiste nada, regresa y vuelve a intentarlo")

def Archivo_personal(request, id_post, username_id):
    post = Archivo.objects.get(id=id_post)
    comments = Comentarios.objects.filter(cm_archivo = post)
    user = Usuario.objects.get(id=username_id)
    
    if user.user_name in post.lista:
        pass

    else:
        post.lista.append(user.user_name)
        post.vistas += 1
        post.save()

    data = {
        'comentarios': comments,
        'post': post,
        'usuario_main': username_id
    }
    return render(request, "archivo.html", data)

def Chekview1(request):
    if request.POST['nombre'] and request.POST['contra']:
        user = request.POST['nombre']
        contra = request.POST['contra']

        try:
            usuario_login = Usuario.objects.get(user_name=user, user_password=contra)
        except ObjectDoesNotExist:
            usuario_login = None

        if usuario_login == None:
            return HttpResponse("Tus datos no son validos, regresa y vuelve a intentarlo")

        else:
            print(f"Usuario {user} inició sesión: {datetime.now}")
            bandera = False
            
            for i in Membership.objects.all():
                if i.usuario == usuario_login:
                    afiliacion = i
                    bandera = True
                    break
            


            if bandera==False:
                return redirect("sala1/"+str(usuario_login.id))

            else:
                canal = afiliacion.canal
                return redirect('home/'+str(usuario_login.id)+'/'+canal.canal_code+'/')
            

    else:
        return HttpResponse("Digite los datos pedidos porfavor")

def Chekview2(request):
    if request.POST["nombre"] and request.POST["contraseña"]:
        
        user = request.POST["nombre"]
        password = request.POST["contraseña"]

        try: 
            imagen = request.FILES["image"]

        except:
            imagen = "images/defecto.jpg"

        obj = Usuario.objects.create(user_name=user,user_password=password ,user_image=imagen)
        obj.save()
        return redirect('sala1/'+str(obj.id))

    else:
        return HttpResponse("No se puede Procesar la solicitud")

def Checkview3(request):
    if request.POST['code'] and request.POST['id_user']: 
        username_id = request.POST['id_user']
        usuario = Usuario.objects.get(id=username_id)
        code = request.POST['code'] 

        try:
            sala = Canal.objects.get(canal_code=code)

        except ObjectDoesNotExist:
            sala = None

        if sala == None:
            return HttpResponse("El codigo ingresado no existe")

        else:
            Membership.objects.create(usuario=usuario, canal=sala) 
            return redirect('home/'+str(username_id)+'/'+code+'/')

    else:
        return HttpResponse("Porfavor llene el campo requerido")

def Checkview4(request):
    if request.POST:
        username_id = request.POST['username_id']
        code = request.POST['code']

        usuario_arc = Usuario.objects.get(id=username_id)
        canal_arc = Canal.objects.get(canal_code=code)
        
        try:
            pdf_arc = request.FILES["pdf"]

        except:
            pdf_arc = "pdfs/Proyecto.pdf"

        titulo_arc = request.POST['titulo']
        descripcion_arc = request.POST['descripcion']
        tipo_arc = request.POST['tipo']
        categoria_arc = request.POST['categoria']

        arc = Archivo.objects.create(archivo=pdf_arc, titulo=titulo_arc, descripcion=descripcion_arc, categoria=categoria_arc, tipo=tipo_arc, usuario=usuario_arc, canal=canal_arc)
        arc.save()

        return redirect('home/'+str(username_id)+'/'+code+'/archivos/')
    else:
        return HttpResponse("Por favor digite los datos solicitados")



def send(request):
    message = request.POST['message']
    username = request.POST['username']
    room_id = request.POST['room_id']
    canalid = Canal.objects.get(canal_code=room_id)
    new_message = Mensaje.objects.create(ms_text=message, ms_user=username, ms_canal=canalid)
    print(f"Nuevo mensaje en sala: {canalid.canal_code}")
    print(f"Fecha: {new_message.tiempo}")
    new_message.save()
    return HttpResponse('Message sent successfully')

def send2(request):
    print("llegue")
    message = request.POST['message']
    user_id = request.POST['username']
    post_id = request.POST['post_id']
    user = Usuario.objects.get(id=user_id)
    archivo = Archivo.objects.get(id=post_id)
    
    new_comentario = Comentarios.objects.create(cm_texto=message, cm_archivo = archivo, cm_user=user.user_name)
    archivo.comments += 1
    archivo.save()
    new_comentario.save()
    print(f"Nuevo comentario en el archivo: {archivo.titulo}")
    print(f"Fecha: {new_comentario.tiempo}")
    return HttpResponse('Message sent successfully')

def getMessages(request, room):
    room_details = Canal.objects.get(codigo=room)

    messages = Mensaje.objects.filter(canal=room_details)
    return JsonResponse({"messages":list(messages.values())})

class DescargarArchivoView(View):
    def post(self, request, *args, **kwargs):
        post = Archivo.objects.get(id=request.POST['id_post'])
        response = HttpResponse(post.archivo, content_type='text/plain')
        response['Content-Disposition'] = 'attachment; filename="%s"' % post.archivo
        return response

Prototipo/Repositorio/templates/Home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HOME</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'CSS/Home.css' %}">
    <script   src="https://code.jquery.com/jquery-3.1.1.min.js"   integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="   crossorigin="anonymous"></script>
</head>
<body>
    <div class="lateral">
        <img class="lateral_avatar" src="{{usuario.user_image.url}}" alt="avatar">
        <p class="lateral_name">{{usuario.user_name}}</p>
        <span class="lateral_codigo"><p class="code">{{sala.canal_code}}</p></span>
        <div class="lateral_exit" >
            <a class="direccion_salir" href="{% url 'Repositorio:Login'%}">SALIR</a>
        </div>
    </div>

    <div class="people">
        <div class="title_group"><p class="title">GRUPO DE LA UNIVERSIDAD</p></div>
        
        <div class="integrantes">
            {% comment %} <div class="card">

                <img class="card_perfil" src="./ok.jpg" alt="persona1">
                <p class="card_name">ANAYELI</p>

                
            </div> {% endcomment %}

            {% for participante in miembros %}
            <div class="card">
                <img class="card_perfil" src="{{participante.user_image.url}}" alt="persona1">
                <p class="card_name">{{participante.user_name}}</p>
            </div>
            {%endfor%}
        </div>
    </div>

    <div class="chat">
        <div class="content_messages">

            {% comment %} <div class="tus_mensajes">
			    <small class="chat_user">anayeli</small>
			    <p class="chat_texto_left">Hola ¿Como estas?</p>
			    <small class="chat_fecha_left">12:12pm</small>
		    </div>

            <div class="mis_mensajes">
			    <small class="chat_user_right">claudia</small>
			    <p class="chat_texto_right">Hola, bien gracias</p>
			    <small class="chat_fecha_right">12:13pm</small>
		    </div> {% endcomment %}

            {% for mensaje in messages %}
            <div class="{% if mensaje.ms_user == usuario.user_name %} mis_mensajes {% else %} tus_mensajes{% endif %}">
			    <small class="chat_user">{{mensaje.ms_user}}</small>
			    <p class="chat_texto">{{mensaje.ms_text}}</p>
			    <small class="chat_fecha">{{mensaje.tiempo}}</small>
		    </div>
            {% endfor %}

        </div>

        <div class="send_messages">
            <form id="post-form">
                {% csrf_token %}
                <input type="hidden" name="username" id="username" value="{{usuario.user_name}}"/>
                <input type="hidden" name="room_id" id="room_id" value="{{sala.canal_code}}"/>                    <input type="text"   name="message" id="message" class="chat_text">
                <input type="submit" class="chat_send" value=">"> 
            </form>
        </div>
    </div>

    <div class="options">
        <div class="content">
            <div class="b_content"><a href="{% url 'Repositorio:archivos' usuario.id sala.canal_code %}">MOSTRAR ARCHIVOS</a></div>
            <div class="b_content"><a href="{% url 'Repositorio:mis_archivos' usuario.id sala.canal_code %}">MIS ARCHIVOS</a></div>
            <div class="b_content"><a href="{% url 'Repositorio:subir' usuario.id sala.canal_code %}">SUBIR ARCHIVO</a></div>
        </div>
    </div>
</body>

<script type="text/javascript">
    $(document).on('submit','#post-form',function(e){
      e.preventDefault();
  
      $.ajax({
        type:'POST',
        url:'/send',
        data:{
            username:$('#username').val(),
            room_id:$('#room_id').val(),
            message:$('#message').val(),
          csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
        },
        success: function(data){
            //alert(data)
         }
       });
      document.getElementById('message').value = ''
  });
  </script>
</html>

Prototipo/Repositorio/templates/canal_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Canal Creado</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'CSS/canal_create.css' %}">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
</head>
<body>

    <div id="particles-js"></div>

    <div class="container">
        <div class="card">
            <p class="create">{{codigo}}</p>
        </div>
    
       <div class="card">
        <form action="{% url 'Repositorio:checkview3' %}" method="POST">
            {%csrf_token%}
            <input type="hidden" name="id_user" value="{{identificador}}">
            <label for="code" class="code_t">Digite el codigo de la sala:</label>
            <input type="text" id="code" class="code">
            
         <input type="submit" class="send" value=">">
        </form>
       </div>

    </div>

    <script src="{% static 'JS/block2.js'%}"></script>
    <script src="{% static 'JS/block2_3.js'%}"></script>
    <script src="{% static 'JS/block2_2.js'%}"></script>
</body>
</html>

Prototipo/Repositorio/templates/canal_main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Canal Main</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'CSS/canal_main.css'%}">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
</head>
<body>

    <div id="particles-js"></div>

    <div class="container">
        <div class="card">
            <form action="{% url 'Repositorio:sala2'%}" method="POST">
                {%csrf_token%}
                <input type="hidden" name="id_user" value="{{id_user}}">
                <input type="submit" id="go" value="CREAR SALA" class="create">
            </form>
        </div>
    
       <div class="card">
        <form action="{% url 'Repositorio:checkview3' %}" method="POST">
            {%csrf_token%}
            <input type="hidden" name="id_user" value="{{id_user}}">
            <label for="code" class="code_t">Digite el codigo de la sala:</label>
            <input type="text" name="code" id="code" class="code">
            
         <input type="submit" class="send" value=">">
        </form>
       </div>

    </div>

    <script src="{% static 'JS/block2.js'%}"></script>
    <script src="{% static 'JS/block2_3.js'%}"></script>
    <script src="{% static 'JS/block2_2.js'%}"></script>
</body>
</html>

Prototipo/Repositorio/templates/form_login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'CSS/form_login.css'%}">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>    
</head>
<body>
    <div id="particles-js"></div>
    <div class="container">
        <form action="{% url 'Repositorio:checkview1'%}" method="POST" class="form">
            {% csrf_token %}
            <h1>LOGIN</h1>
            
            <p type="Nombre de Usuario:">
                <input placeholder="Escribe tu alias aqui..." name="nombre" requerided></input>
            </p>
            <p type="Contraseña:">
                <input type="password" placeholder="Escribe tu contraseña aqui..." name="contra" requerided></input>
            </p>
            
            <a href="{% url 'Repositorio:Registrarse' %}"> ¿No tienes cuenta? </a>
            <input type="submit" value="LOGIN" class="button"></input>
          </form>
    </div>
    

    <script src="{% static 'JS/block2.js'%}"></script>
    <script src="{% static 'JS/block2_3.js'%}"></script>
    <script src="{% static 'JS/block2_2.js'%}"></script>
    <script src="{% static 'JS/file.js'%}"></script>
</body>
</html>

Prototipo/Repositorio/templates/form_register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registar</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'CSS/form_register.css'%}">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>    
</head>
<body>
    <div id="particles-js"></div>
    <div class="container">
        <form action="{% url 'Repositorio:checkview2'%}" method="POST" class="form" enctype="multipart/form-data">
            {% csrf_token %}
            <h1>REGISTRATE</h1>
            <div class="form-file">
                <div class="form-file__action">
                    <input type="file" name="image" id="image" />
                </div>
                <div class="form-file__result" id="result-image">
                    <img id="img-result" alt="" />
                </div>
            </div>
            
            <p type="Nombre de Usuario:">
                <input placeholder="Escribe tu alias aqui..." name="nombre" requerided></input>
            </p>
            <p type="Contraseña:">
                <input type="password" placeholder="Escribe tu contraseña aqui..." name="contraseña" requerided></input>
            </p>
        
            <input type="submit" value="REGISTRAR" class="button"></input>
          </form>
    </div>
    

    <script src="{% static 'JS/block2.js'%}"></script>
    <script src="{% static 'JS/block2_3.js'%}"></script>
    <script src="{% static 'JS/block2_2.js'%}"></script>
    <script src="{% static 'JS/file.js'%}"></script>
</body>
</html>

Prototipo/Repositorio/templates/mostrar_archivos.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Mostrar Archivos</title>
	{% load static %}
	<link rel="stylesheet" href="{% static 'CSS/mostrar_archivos.css'%}">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
	<script src="https://code.jquery.com/jquery-3.4.1.js"></script>
</head>
<body>
	
	<div class="lateral">
		<img src="" alt="">
	</div>

	<div class="arriba">
		<form class="container" id="lupa" action="{%url 'Repositorio:resultados' %}" method="POST">
			{% csrf_token %}
			<input type="hidden" name="username_id" value="{{username_id}}"/>
			<input type="hidden" name="code" value="{{code}}"/>
			<input type="c_text" name="palabra" placeholder="Buscar">
			<div class="btn">
				<i class="fa fa-search"></i>
			</div>
		</form>

		<div class="retroceder">
			<a href="{%url 'Repositorio:home' username_id code %}">Atras</a>
		

			{% comment %} <form method="post" action="{% url 'Repositorio:archivo_post' %}">
            {% csrf_token %}

            	<input type="hidden" name="id_post" value="1"/>
            	<input type="submit" class="btn btn-primary" type="button" value="Ver">
        	</form> {% endcomment %}
		</div>
	</div>

	<div class="articulos">

		{%for elemento in archivos%}

		<div class="card">

			<div class="card-image">
				<object class="pdf" data="{{elemento.archivo.url}}" type="application/pdf" width="300px" height="230px"></object>
				{% comment %} <object class="pdf" data="/media/pdfs/Proyecto.pdf" type="application/pdf" width="300px" height="230px"></object> {% endcomment %}
				{% comment %} <embed class="pdf" src="{{elemento.archivo.url}}" type="application/pdf" width="300px" height="230px" /> {% endcomment %}
				{% comment %} <iframe src="{{elemento.archivo.url}}" frameborder="0"></iframe> {% endcomment %}
				{% comment %} <iframe src="{%url 'Repositorio:archivo_post'%}", frameborder="0"></iframe> {% endcomment %}
			</div>

			<div class="card-text">
				<span class="date">{{elemento.tiempo}}</span>
				<h2>{{elemento.titulo}}</h2>
				<p> <b>Autor: {{elemento.usuario.user_name}}</b> <br> {{elemento.descripcion}}</p>
			</div>
			
			<div class="card-stats">
				<div class="stat">
					<div class="value">Tipo:</div>
					<div class="value">{{elemento.tipo}}</div>
				</div>
			
				<div class="stat border">
					<div class="value">{{elemento.comments}}</div>
					<div class="type">comentarios</div>
				</div>
			
				<div class="stat">
					<div class="value">{{elemento.vistas}}</div>
					<a href="{%url 'Repositorio:archivo_personal' elemento.id username_id%}" class="redireccionar">Ver</a>
				</div>
			</div>
		</div>
		{% endfor %}
		
	</div>

	<script>
		$(document).ready(function(){
		  $('.content').click(function(){
			$('.content').toggleClass("heart-active")
			$('.text').toggleClass("heart-active")
			$('.numb').toggleClass("heart-active")
			$('.heart').toggleClass("heart-active")
		  });
		  
		});
	</script>
</body>
</html>